Use CoffeeDB

CREATE TABLE [dbo].[Location](
    [ID] [int] IDENTITY(1,1) NOT NULL,
    [LocationName] [varchar](50) NOT NULL,
    [Description] [varchar](100) NULL
 CONSTRAINT [PK_Location] PRIMARY KEY CLUSTERED 
(
    [ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON)
) ON [PRIMARY]


CREATE TABLE [dbo].[Ingredient](
    [ID] [int] IDENTITY(1,1) NOT NULL,
    [IngredientName] [varchar](50) NOT NULL,
	[Stock] [int] NOT NULL,
    [Description] [varchar](100) NULL,
	[LocationId] [int] NULL
 CONSTRAINT [PK_Ingredient] PRIMARY KEY CLUSTERED 
(
    [ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON)
) ON [PRIMARY]


CREATE TABLE [dbo].[Recipe](
    [ID] [int] IDENTITY(1,1) NOT NULL,
	[CoffeeId] [int] NOT NULL,
    [IngredientId] [int] NOT NULL,
	[Amount] [int] NOT NULL
 CONSTRAINT [PK_Recipe] PRIMARY KEY CLUSTERED 
(
    [ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON)
) ON [PRIMARY]


CREATE TABLE [dbo].[Coffee](
    [ID] [int] IDENTITY(1,1) NOT NULL,
    [CoffeeName] [varchar](50) NOT NULL,	
    [Description] [varchar](100) NULL

 CONSTRAINT [PK_Coffee] PRIMARY KEY CLUSTERED 
(
    [ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON)
) ON [PRIMARY]
